### ISSUE TITLE
when i run the DingDongBot examples local,found a exception

### ISSUE THREAD

**Issue by kill8ug** [wechaty/java-wechaty-getting-started#16]
Why did I get Failed to connect to api.chatie.io ?

```
[java.net.SocketTimeoutException: connect timed out, java.net.SocketTimeoutException: connect timed out, java.net.SocketTimeoutException: connect timed out, java.net.ConnectException: Failed to connect to api.chatie.io/2606:4700:3031:0:0:0:xxxx:4881:443, java.net.ConnectException: Failed to connect to api.chatie.io/2606:4700:3031:0:0:0:xxxx:4981:443]
14:03:01.581 [main]ERROR io.github.wechaty.grpc.GrpcPuppet-[79]  - start() rejection:
java.net.ConnectException: Failed to connect to api.chatie.io/2606:4700:3036:0:0:0:xxxx:c20c:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:285) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) ~[okhttp-4.6.0.jar:?]
	at io.github.wechaty.grpc.GrpcPuppet.discoverHostieIpa(GrpcPuppet.kt:50) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
	at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:135) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:71) [wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
	at io.github.wechaty.Wechaty.start(Wechaty.kt:42) [wechaty-1.0.0-20200524.113740-2.jar:?]
	at io.github.wechaty.DingDongBot.main(DingDongBot.java:49) [classes/:?]
	Suppressed: java.net.SocketTimeoutException: connect timed out
		at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
		at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) ~[okhttp-4.6.0.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.discoverHostieIpa(GrpcPuppet.kt:50) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:135) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:71) [wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.Wechaty.start(Wechaty.kt:42) [wechaty-1.0.0-20200524.113740-2.jar:?]
		at io.github.wechaty.DingDongBot.main(DingDongBot.java:49) [classes/:?]
	Suppressed: java.net.SocketTimeoutException: connect timed out
		at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
		at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) ~[okhttp-4.6.0.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.discoverHostieIpa(GrpcPuppet.kt:50) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:135) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:71) [wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.Wechaty.start(Wechaty.kt:42) [wechaty-1.0.0-20200524.113740-2.jar:?]
		at io.github.wechaty.DingDongBot.main(DingDongBot.java:49) [classes/:?]
	Suppressed: java.net.SocketTimeoutException: connect timed out
		at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
		at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) ~[okhttp-4.6.0.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.discoverHostieIpa(GrpcPuppet.kt:50) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:135) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:71) [wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.Wechaty.start(Wechaty.kt:42) [wechaty-1.0.0-20200524.113740-2.jar:?]
		at io.github.wechaty.DingDongBot.main(DingDongBot.java:49) [classes/:?]
	Suppressed: java.net.ConnectException: Failed to connect to api.chatie.io/2606:4700:3031:0:0:0:xxxx:4881:443
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:285) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) ~[okhttp-4.6.0.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.discoverHostieIpa(GrpcPuppet.kt:50) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:135) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:71) [wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.Wechaty.start(Wechaty.kt:42) [wechaty-1.0.0-20200524.113740-2.jar:?]
		at io.github.wechaty.DingDongBot.main(DingDongBot.java:49) [classes/:?]
	Caused by: java.net.ConnectException: No route to host (connect failed)
		at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
		at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283) ~[okhttp-4.6.0.jar:?]
		... 20 more
	Suppressed: java.net.ConnectException: Failed to connect to api.chatie.io/2606:4700:3031:0:0:0:xxxx:4981:443
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:285) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) ~[okhttp-4.6.0.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.discoverHostieIpa(GrpcPuppet.kt:50) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:135) ~[wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:71) [wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
		at io.github.wechaty.Wechaty.start(Wechaty.kt:42) [wechaty-1.0.0-20200524.113740-2.jar:?]
		at io.github.wechaty.DingDongBot.main(DingDongBot.java:49) [classes/:?]
	Caused by: java.net.ConnectException: No route to host (connect failed)
		at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
		at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119) ~[okhttp-4.6.0.jar:?]
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283) ~[okhttp-4.6.0.jar:?]
		... 20 more
Caused by: java.net.ConnectException: No route to host (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119) ~[okhttp-4.6.0.jar:?]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283) ~[okhttp-4.6.0.jar:?]
	... 20 more
14:03:01.601 [main]WARN  io.github.wechaty.eventEmitter.EventEmitter-[44]  - this eventName:start has no listener
```

**Comment by huan** [comment]
> java.net.ConnectException:
> Failed to connect to
> api.chatie.io/2606:4700:3036:0:0:0:xxxx:c20c:443

It seems that your system resolved an IPv6 for the domain api.chatie.io but can not connect to it.

Do you have an IPv6 enabled networking?
