### ISSUE TITLE
my wechaty token gate server  seems to be a problem

### ISSUE THREAD

**Issue by kill8ug** [wechaty/java-wechaty-getting-started#17]
from:
[https://github.com/wechaty/wechaty/issues/1985](url)

i make a token gate server ,
but when i start my DingDongBot by idea,
found a exception following

### **maven build or gitpod ,my token** 

```
07:05:49.999 [main]ERROR io.github.wechaty.grpc.GrpcPuppet-[153]  - cannot get ip by token, check token
07:05:50.001 [main]ERROR io.github.wechaty.grpc.GrpcPuppet-[84]  - start() rejection:
java.lang.Exception: cannot get ip by token, check token
        at io.github.wechaty.grpc.GrpcPuppet.startGrpcClient(GrpcPuppet.kt:154) ~[wechaty-examples-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:76) [wechaty-examples-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at io.github.wechaty.Wechaty.start(Wechaty.kt:42) [wechaty-examples-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at io.github.wechaty.DingDongBot.main(DingDongBot.java:48) [wechaty-examples-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
07:05:50.016 [main]WARN  io.github.wechaty.eventEmitter.EventEmitter-[44]  - this eventName:start has no listener
07:05:50.017 [main]INFO  io.github.wechaty.Wechaty-[48]  - start Wechaty
07:06:48.505 [pool-6-thread-1]INFO  io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[50]  - sent reset message
07:06:48.507 [pool-5-thread-1]INFO  io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[34]  - sent reset message
07:06:48.508 [pool-5-thread-1]INFO  io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[66]  - feed dog WatchdogFood(timeout=60000, data=null)
07:06:48.508 [pool-5-thread-1]INFO  io.github.wechaty.io.github.wechaty.watchdag.WatchdogFood-[77]  - lastFeed is 1590649608508`


### my local  ,the same token :

`15:07:04.931 [main]INFO  io.github.wechaty.grpc.GrpcPuppet-[73]  - IDLE
15:07:05.182 [main]ERROR io.github.wechaty.grpc.GrpcPuppet-[79]  - start() rejection:
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [HttpClientCodec#0, HttpProxyHandler#0, ProtocolNegotiators$ProxyProtocolNegotiationHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240) ~[grpc-stub-1.25.0.jar:1.25.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221) ~[grpc-stub-1.25.0.jar:1.25.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140) ~[grpc-stub-1.25.0.jar:1.25.0]
	at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.start(PuppetGrpc.java:2731) ~[grpc-0.11.25.jar:?]
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:75) [wechaty-puppet-hostie-1.0.0-20200524.113647-2.jar:?]
	at io.github.wechaty.Wechaty.start(Wechaty.kt:42) [wechaty-1.0.0-20200524.113740-2.jar:?]
	at io.github.wechaty.DingDongBot.main(DingDongBot.java:48) [classes/:?]
Caused by: io.grpc.netty.shaded.io.netty.handler.proxy.ProxyConnectException: http, none, /127.0.0.1:1090 => 106.53.228.235:8788, disconnected
	at io.grpc.netty.shaded.io.netty.handler.proxy.ProxyHandler.channelInactive(ProxyHandler.java:236) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:393) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:358) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:285) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1417) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:913) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.25.0.jar:1.25.0]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]
15:07:05.191 [main]WARN  io.github.wechaty.eventEmitter.EventEmitter-[44]  - this eventName:start has no listener
```

**Comment by chengaopan** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/18641281/83208753-1863b300-a189-11ea-83f3-333601503d93.png)

**Comment by diaozxin007** [comment]
plz try it again. if have same problem. try to delete the wechaty from your .m2 folder.

**Comment by chengaopan** [comment]
I have tried your method, but it is useless. It still prompts the same problem. Is my token wrong

The token  format looks like this  puppet_padplus_xxxxxxxxxx

**Comment by bestK** [comment]
+1
