### ISSUE TITLE
Unable to listen to group chat joining information

### ISSUE THREAD

**Issue by wangtianlei001** [wechaty/java-wechaty-getting-started#21]
/**
         * 监听群聊加入
         */
        bot.on("RoomJoin",(RoomJoinListener) (room, list, contact, date) -> {
            String message = "欢迎";
            list.forEach(item-> System.out.println(item.getAlias()));
            room.say(message,list);
        });

**Comment by diaozxin007** [comment]
try modify “RoomJoin” to “room-join”. we will use enum to replace the string in next version.

**Comment by huan** [comment]
Awesome, enum will help developers to make sure the they are not using the wrong event names.

One question: can Java use the same event name as the TS with the enum values?

**Comment by wangtianlei001** [comment]
@huan if it same with ts ,will help with development

**Comment by wangtianlei001** [comment]
I changed the code RoomJoin  to room-join, but this event will cause the robot to fail to receive group chat messages

**Comment by wangtianlei001** [comment]
本地运行正常，生成jar包部署到服务器时抛异常。可以正常显示二维，但是不打印日志
[Fatal Error] log4j2.xml:14:1: 文件提前结束。
ERROR StatusLogger Error parsing jar:file:/D:/wechaty-examples-1.0.0-SNAPSHOT-jar-with-dependencies.jar!/log4j2.xml
 org.xml.sax.SAXParseException; systemId: jar:file:/D:/wechaty-examples-1.0.0-SNAPSHOT-jar-with-dependencies.jar!/log4j2.xml; lineNumber: 14; columnNumber: 1; 文件提前结束。
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:92)
        at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:532)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:456)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:318)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:687)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at io.github.wechaty.eventEmitter.EventEmitter.<clinit>(EventEmitter.kt:114)
        at io.github.wechaty.DingDongBot.main(DingDongBot.java:27)
ERROR StatusLogger No logging configuration

**Comment by diaozxin007** [comment]
@wangtianlei001 plz try new api
