### ISSUE TITLE
启动的时候io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

### ISSUE THREAD

**Issue by George4142** [wechaty/java-wechaty-getting-started#34]
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244) ~[grpc-stub-1.29.0.jar:1.29.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225) ~[grpc-stub-1.29.0.jar:1.29.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142) ~[grpc-stub-1.29.0.jar:1.29.0]
	at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.start(PuppetGrpc.java:2744) ~[grpc-0.16.1.jar:?]
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:78) [wechaty-puppet-hostie-0.1.5-SNAPSHOT.jar:?]
	at io.github.wechaty.Wechaty.start(Wechaty.kt:52) [wechaty-0.1.5-SNAPSHOT.jar:?]
	at io.github.wechaty.DingDongBot.main(DingDongBot.java:49) [classes/:?]

**Comment by George4142** [comment]
docker 换成了wechaty:0.56的版本就可以了。目测应该是docker和sdk的grpc版本不符

**Comment by huan** [comment]
You are running into 

- https://github.com/wechaty/wechaty-puppet-service/issues/160

## Solution

https://wechaty.js.org/docs/puppet-services/diy/#6-config-tlsssl-for-wechaty-puppet-service-optional

**Comment by Nanmen** [comment]
> docker 换成了wechaty:0.56的版本就可以了。目测应该是docker和sdk的grpc版本不符

TLS要设置成true么？能麻烦给个联系方式，我这边用0.56还是起不起来

**Comment by George4142** [comment]
> You are running into
> 
> * [Enable TLS for all Puppet Service Clients of Wechaty Ecosystem wechaty-puppet-service#160](https://github.com/wechaty/wechaty-puppet-service/issues/160)
> 
> ## Solution
> https://wechaty.js.org/docs/puppet-services/diy/#6-config-tlsssl-for-wechaty-puppet-service-optional

谢谢~

**Comment by huan** [comment]
@George4142 You are welcome!

**Comment by George4142** [comment]
还有个新问题：发送文字是乱码
测试测试1�?�?�?�?�?UTF-8


测试测试1�?�?�?�?�?GBK


娴�璇�娴�璇�1涓?涓?涓?涓?涓?GB2312

æµè¯æµè¯1ä¸?ä¸?ä¸?ä¸?ä¸?ISO-8859-1


诨꾕诨꾕㇤렿㿤렿㿤렿Unicode

**Comment by coloforlia** [comment]
> @George4142 You are welcome!

why i cannot run this demo with  wechaty/wechaty:1.13
