### ISSUE TITLE
企业微信登录，扫码之后在哪里输入验证码，docker日志提示输入验证码

### ISSUE THREAD

**Issue by 15638192475** [wechaty/java-wechaty-getting-started#41]
![微信图片_20240226223515](https://github.com/wechaty/java-wechaty-getting-started/assets/45378602/61aeaf6c-6c7f-4a70-96e5-215e80ccd295)

**Comment by 15638192475** [comment]
Online QR Code Image: https://wechaty.js.org/qrcode/https%3A%2F%2Fwx.work.weixin.qq.com%2Fcgi-bin%2Fcrtx_auth%3Fkey%3D10F9F4F3A779C0A7AA42499A437B846A%26wx%3D1
14:31:56 VERB EventStreamManager grpcEmit(EVENT_TYPE_SCAN[22], {"qrcode":"https://wx.work.weixin.qq.com/cgi-bin/crtx_auth?key=10F9F4F3A779C0A7AA42499A437B846A&wx=1","type":1,"timestamp":1708957684801,"createTimestamp":1708957684801,"expireTimestamp":1708958284801})
14:31:56 VERB PuppetService onGrpcStreamEvent({type:undefined(33), payload:"{"id":"10F9F4F3A779C0A7AA42499A437B846A","message":"请输入企业微信手机端展示的验证码，以继续登录","scene":1,"status":1}"})
14:31:56 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"onGrpcStreamEvent(undefined)","timeout":60000})
14:31:56 ERR Config ###########################
14:31:56 ERR Config uncaughtException: Error: eventType 33 unsupported! (code should not reach here)
    at PuppetService.onGrpcStreamEvent (/wechaty/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:578:15)
    at ClientReadableStreamImpl.emit (events.js:400:28)
    at ClientReadableStreamImpl.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at ClientReadableStreamImpl.Readable.push (internal/streams/readable.js:204:10)
    at Object.onReceiveMessage (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:565:16)
    at Object.onReceiveMessage (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:383:47)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:346:22
    at processTicksAndRejections (internal/process/task_queues.js:77:11) uncaughtException
